services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend

      - user_media:/app/backend/media
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      - DEVELOPMENT_DATABASE=postgres
      - DJANGO_SUPERUSER_EMAIL=admin@a.io
      - DJANGO_SUPERUSER_FIRST_NAME=admin
      - DJANGO_SUPERUSER_LAST_NAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn start
  db:
    image: postgres:11.1-alpine

  caddy:
    image: caddy:2.8-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - user_media:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ROOT_URL=localhost
    ports:
      - "9000:443"
      - "9001:80"

volumes:
  user_media:
  caddy_data:
  caddy_config:

